spring.application.name=boltfood

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.liquibase.default-schema=PUBLIC
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Admin
spring.datasource.password=Admin

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

weather.api.url=https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php
weather.import.cron=0 15 * * * *

http.connection-timeout=5000
http.read-timeout=20000